### ISSUE TITLE
Bridge non détecté

### ISSUE THREAD

**Issue by Steve-MD** [GladysProject/gladys-milight#1]
Bonjour,

Je ne sais pas si c'est vraiment un bug, car étant "newbie" l'erreur vient peut-être de moi. En effet je suis à la lettre la procédure: l'installation du module s'effectue sans problème, je redémarre Gladys, mais quand je clique sur "Configurer" j'ai bien le message qui m'indique que la configuration s'est bien effectuée, néanmoins mon bridge n'apparaît pas dans mes devices.

J'ai recommencé l'opération plusieurs fois, et je me suis assuré que le Wi-Fi du Raspberry Pi 3 fonctionnait bien au cas où le problème viendrait de là. J'ai également essayé de débrancher puis rebrancher mon bridge avant de cliquer sur "Configurer", ainsi qu'un appui sur le bouton reset du bridge avant de cliquer, mais toujours rien.

Y a-t-il une étape que j'ai manquée? Quelqu'un pourrait-il détailler l'utilisation de ce module Mi-Light?

D'avance merci.

PS: Super projet, je suis sur Raspberry Pi 3 avec une carte SD de 16 Gb et la version 3.3.4 de Gladys.

**Comment by TuxxyDOS** [comment]
Même chose pour moi

**Comment by Pierre-Gilles** [comment]
Hello !

Désolé de la non-réponse, j'ai du complètement zapper l'issue à l'époque :) 

Pour tout problème d'installation, le plus simple est d'aller poser ta question sur le forum Gladys => http://community.gladysproject.com/

C'est beaucoup plus actif que les issues GitHub !

Bonne journée,
